/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.mipt.spring2014.class04.cust_gui;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author Andrei
 */
public class GraphDemoWindow extends javax.swing.JFrame
{
	/**
	 * Creates new form GraphDemoWindow
	 */
	public GraphDemoWindow ()
	{
		initComponents ();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphPanel = new GraphPanel ();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void formKeyPressed (java.awt.event.KeyEvent evt)//GEN-FIRST:event_formKeyPressed
	{//GEN-HEADEREND:event_formKeyPressed
		/*
		 * Простейшая реализация обработки нажатия клавиш:
		 * 1) если нажата одна из 4х клавиш со стрелками, сообщаем о направлении стрелки,
		 * 2) во всех остальных случаях выводим код клавиши.
		 */
		switch (evt.getKeyCode ())
		{
			case KeyEvent.VK_UP:
				System.out.println ("Up pressed");
				break;
			case KeyEvent.VK_DOWN:
				System.out.println ("Down pressed");
				break;
			case KeyEvent.VK_LEFT:
				System.out.println ("Left pressed");
				break;
			case KeyEvent.VK_RIGHT:
				System.out.println ("Right pressed");
				break;
			default:
				System.out.println ("Key pressed: " + evt.getKeyCode ());
		}
	}//GEN-LAST:event_formKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphPanel;
    // End of variables declaration//GEN-END:variables
}
